### ISSUE TITLE
Related project founded

### ISSUE THREAD

**Issue by titipat** [tmwatchanan/cpe412-api#1]
I found @chawasit and his friends are working on project https://github.com/cpe24fundb/412-Shop which related to your project. Any potential to integrate with their work?

Thank you :)

**Comment by tmwatchanan** [comment]
I talked to him about this project a few days ago. We have planned to use Play Framework mainly based on Scala language. I am taking time in studying Scala now. By the way, we might discuss about the project you mentioned again krub. Thanks a bunch!
